### ISSUE TITLE
Ventana para minimapa

### ISSUE THREAD

**Issue by fbalboadv** [Ayusmi/Motores-2-TP#5]
Que pueda crear un minimapa, esto debería incluir la cámara si no la tiene. Que pueda personalizar lo más posible.

**Comment by stylux0** [comment]
Por ahora se puede agregar una camara, con su respectiva vista en la escena (por medio de una imagen y texture).
**Aun el tema grafico y la navegación por la ventana no estan acomodadas ni resueltos.**

**Comment by stylux0** [comment]
Se agrega la camara, elegir la "altura" de esta y se puede personalizar el tamaño del minimapa. 
**Sin personalizacion grafica y tampoco de posición. **
